# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180208_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
