# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'ESTANDAR'), (2, 'desarrollador')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'estandar'), (2, 'desarrollador')], default=1),
            preserve_default=False,
        ),
    ]
