# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180212_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'estandar'), (2, 'desarrollador')], null=True),
        ),
    ]
